export const CREATE_WISHLIST_ENTRY = "CREATE_WISHLIST_ENTRY";
export const LOAD_POKEMON_SUCCESS = "LOAD_POKEMON_SUCCESS";
export const LOAD_POKEMON_DETAILS_SUCCESS = "LOAD_POKEMON_DETAILS_SUCCESS";
export const LOAD_ABILITIES_DETAILS_SUCCESS = "LOAD_ABILITIES_DETAILS_SUCCESS";
